---
- name: Install apache and php
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: present
      systemd:
        state: started
        name: apache2